<?php

/**
 * @file
 * Basic authentication login - install file.
 */

/**
 * Migrate variables to config.
 */
function restws_basic_auth_update_1000() {
  // Migrate variables to config.
  $config = config('restws.settings');
  $config->set('restws_basic_auth_user_regex', update_variable_get('restws_basic_auth_user_regex', '/^restws.*/'));
  $config->save();

  // Delete variables.
  update_variable_del('restws_basic_auth_user_regex');
}
